# Generated by Django 5.2.8 on 2025-11-24 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("rejs", "0003_rejs_cena_rejs_zaliczka_zgloszenie_status_finanse_and_more"),
	]

	operations = [
		migrations.AlterField(
			model_name="finanse",
			name="zgloszenie",
			field=models.OneToOneField(
				on_delete=django.db.models.deletion.CASCADE,
				related_name="finanse",
				to="rejs.zgloszenie",
			),
		),
	]
