# Generated by Django 5.2.8 on 2025-11-26 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("rejs", "0005_zgloszenie_wzrok_wachta"),
	]

	operations = [
		migrations.RemoveField(
			model_name="wachta",
			name="czlonkowie",
		),
		migrations.AddField(
			model_name="zgloszenie",
			name="wachta",
			field=models.ForeignKey(
				blank=True,
				null=True,
				on_delete=django.db.models.deletion.SET_NULL,
				related_name="czlonkowie",
				to="rejs.wachta",
			),
		),
	]
