# Generated by Django 5.2.8 on 2025-12-02 12:30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("rejs", "0007_alter_wplata_options_info"),
	]

	operations = [
		migrations.AlterModelOptions(
			name="finanse",
			options={"verbose_name": "finanse", "verbose_name_plural": "finanse"},
		),
		migrations.AddField(
			model_name="zgloszenie",
			name="token",
			field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
		),
	]
