# Generated by Django 5.2.8 on 2025-12-19 23:41

import datetime
import django.db.models.deletion
import django.utils.timezone
import rejs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0010_remove_wplata_finanse_wplata_rodzaj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogloszenie',
            options={'verbose_name': 'Ogłoszenie', 'verbose_name_plural': 'Ogłoszenia'},
        ),
        migrations.AlterModelOptions(
            name='wachta',
            options={'verbose_name': 'Wachta', 'verbose_name_plural': 'Wachty'},
        ),
        migrations.AlterModelOptions(
            name='wplata',
            options={'verbose_name': 'Wpłata', 'verbose_name_plural': 'Wpłaty'},
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='data_urodzenia',
            field=models.DateField(default=datetime.date(2025, 12, 20), verbose_name='data urodzenia'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='data_zgloszenia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='obecnosc',
            field=models.BooleanField(default=False, help_text='czy uczestniczyłeś/łaś w innych rejsach zobaczyć morze? zaznacz pole.', verbose_name='uczestnictwo w zobaczyć morze'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='rodo',
            field=models.BooleanField(default=False, help_text='zgadzam się na przetwarzanie danych osobowych zgodnie z polityką prywatności zobaczyć morze.', verbose_name='zgoda na przetwarzanie danych osobowych'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='rola',
            field=models.CharField(choices=[('ZALOGANT', 'załogant'), ('OFICER-WACHTY', 'oficer wachty')], default='ZALOGANT', max_length=25),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='text',
            field=models.TextField(default='krótka informacja o rejsie', verbose_name='Tekst'),
        ),
        migrations.AlterField(
            model_name='ogloszenie',
            name='tytul',
            field=models.CharField(default='nowe ogłoszenie', max_length=100, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='do',
            field=models.DateField(verbose_name='data do'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='koniec',
            field=models.CharField(max_length=200, verbose_name='port końcowy'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='od',
            field=models.DateField(verbose_name='data od'),
        ),
        migrations.AlterField(
            model_name='rejs',
            name='start',
            field=models.CharField(max_length=200, verbose_name='port początkowy'),
        ),
        migrations.AlterField(
            model_name='wplata',
            name='rodzaj',
            field=models.CharField(choices=[('wplata', 'Wpłata'), ('zwrot', 'Zwrot')], default=('zwrot', 'Zwrot'), max_length=7),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adres e-mail'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='imie',
            field=models.CharField(max_length=100, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='nazwisko',
            field=models.CharField(max_length=100, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='status',
            field=models.CharField(choices=[('QUALIFIED', 'Zakwalifikowany'), ('NOT_QUALIFIED', 'Niezakwalifikowany'), ('ODRZUCONE', 'Odrzucone')], default=('NOT_QUALIFIED', 'Niezakwalifikowany'), max_length=20),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='telefon',
            field=models.CharField(max_length=15, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='wzrok',
            field=models.CharField(choices=[('WIDZI', 'widzący'), ('NIEWIDOMY', 'niewidomy'), ('SLABO-WIDZACY', 'słabo widzący')], default=('WIDZI', 'widzący'), max_length=15, verbose_name='Status wzroku'),
        ),
        migrations.CreateModel(
            name='Dane_Dodatkowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poz1', rejs.models.EncryptedTextField(default='12345678900', max_length=13, verbose_name='pesel')),
                ('poz2', rejs.models.EncryptedTextField(choices=[('paszport', 'paszport'), ('dowod-osobisty', 'dowód osobisty')], default=('paszport', 'paszport'), max_length=14, verbose_name='typ dokumentu')),
                ('poz3', rejs.models.EncryptedTextField(default='ABC123', verbose_name='numer dokumentu')),
                ('zgloszenie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dane_dodatkowe', to='rejs.zgloszenie')),
            ],
            options={
                'verbose_name': 'dane dodatkowe',
                'verbose_name_plural': 'dane dodatkowe',
            },
        ),
    ]
