# Generated by Django 5.2.8 on 2025-12-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("rejs", "0013_alter_zgloszenie_data_urodzenia_and_more"),
	]

	operations = [
		migrations.AlterField(
			model_name="zgloszenie",
			name="status",
			field=models.CharField(
				choices=[
					("Niezakwalifikowany", "Niezakwalifikowany"),
					("Zakwalifikowany", "Zakwalifikowany"),
					("Odrzucone", "Odrzucone"),
				],
				default="Niezakwalifikowany",
				max_length=20,
			),
		),
	]
