# Generated by Django 5.2.8 on 2025-12-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0015_alter_dane_dodatkowe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='adres',
            field=models.CharField(default='unknown'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='kod_pocztowy',
            field=models.CharField(default='00-000', verbose_name='kod pocztowy'),
        ),
        migrations.AddField(
            model_name='zgloszenie',
            name='miejscowosc',
            field=models.CharField(default='unknown'),
        ),
    ]
