# Generated by Django 5.2.8 on 2026-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0020_alter_zgloszenie_data_urodzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenie',
            name='adres',
            field=models.CharField(default='adres'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='miejscowosc',
            field=models.CharField(default='miejscowość'),
        ),
    ]
