# Generated by Django 6.0 on 2025-12-24 10:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("rejs", "0021_dodanie_zgody_dane_wrazliwe"),
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
	]

	operations = [
		migrations.CreateModel(
			name="AuditLog",
			fields=[
				(
					"id",
					models.BigAutoField(
						auto_created=True,
						primary_key=True,
						serialize=False,
						verbose_name="ID",
					),
				),
				(
					"timestamp",
					models.DateTimeField(
						db_index=True,
						default=django.utils.timezone.now,
						verbose_name="Data i czas",
					),
				),
				(
					"akcja",
					models.CharField(
						choices=[
							("odczyt", "Odczyt danych"),
							("utworzenie", "Utworzenie danych"),
							("modyfikacja", "Modyfikacja danych"),
							("usuniecie", "Usunięcie danych"),
							("eksport", "Eksport danych"),
						],
						max_length=20,
						verbose_name="Akcja",
					),
				),
				("model_name", models.CharField(max_length=100, verbose_name="Model")),
				(
					"object_id",
					models.PositiveIntegerField(blank=True, null=True, verbose_name="ID obiektu"),
				),
				(
					"object_repr",
					models.CharField(blank=True, max_length=200, verbose_name="Reprezentacja obiektu"),
				),
				(
					"ip_address",
					models.GenericIPAddressField(blank=True, null=True, verbose_name="Adres IP"),
				),
				("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
				(
					"szczegoly",
					models.TextField(blank=True, verbose_name="Szczegóły operacji"),
				),
				(
					"uzytkownik",
					models.ForeignKey(
						blank=True,
						null=True,
						on_delete=django.db.models.deletion.SET_NULL,
						related_name="audit_logs",
						to=settings.AUTH_USER_MODEL,
						verbose_name="Użytkownik",
					),
				),
			],
			options={
				"verbose_name": "Log audytu",
				"verbose_name_plural": "Logi audytu",
				"ordering": ["-timestamp"],
				"indexes": [
					models.Index(
						fields=["model_name", "object_id"],
						name="rejs_auditl_model_n_40f8c9_idx",
					),
					models.Index(
						fields=["uzytkownik", "timestamp"],
						name="rejs_auditl_uzytkow_10b1da_idx",
					),
				],
			},
		),
	]
