# Generated by Django 5.2.8 on 2026-01-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0022_zgloszenie_rozmiar_koszulki_zgloszenie_uwagi'),
    ]

    operations = [
        migrations.AddField(
            model_name='zgloszenie',
            name='plec',
            field=models.CharField(choices=[('kobieta', 'kobieta'), ('mezczyzna', 'mężczyzna'), ('inna', 'inna')], default='inna', max_length=10, verbose_name='płeć'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='rola',
            field=models.CharField(choices=[('ZALOGANT', 'załogant'), ('OFICER-WACHTY', 'oficer wachty'), ('starszy-oficer', 'starszy oficer')], default='ZALOGANT', max_length=25),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='wzrok',
            field=models.CharField(choices=[('WIDZI', 'widzący'), ('NIEWIDOMY', 'niewidomy'), ('SLABO-WIDZACY', 'słabo widzący'), ('lekko-slabo-widzacy', 'lekko słabo widzący'), ('bardzo-slabo-widzacy', 'bardzo słabo widzący'), ('prawie-niewidzacy', 'prawie niewidomy')], default=('WIDZI', 'widzący'), max_length=25, verbose_name='Status wzroku'),
        ),
    ]
