# Generated by Django 5.2.8 on 2026-01-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0023_zgloszenie_plec_alter_zgloszenie_rola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenie',
            name='adres',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='kod_pocztowy',
            field=models.CharField(verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='miejscowosc',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='plec',
            field=models.CharField(choices=[('kobieta', 'kobieta'), ('mezczyzna', 'mężczyzna'), ('inna', 'inna')], max_length=10, verbose_name='płeć'),
        ),
    ]
