# Generated by Django 5.2.8 on 2026-01-13 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0024_alter_zgloszenie_adres_alter_zgloszenie_kod_pocztowy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatnoscPayU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payu_order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.CharField(choices=[('zaliczka', 'Zaliczka'), ('reszta', 'Reszta')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'Nowa'), ('PENDING', 'W toku'), ('COMPLETED', 'Zakończona'), ('FAILED', 'Błąd')], default='NEW', max_length=20)),
                ('utworzona', models.DateTimeField(auto_now_add=True)),
                ('zgloszenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platnosci_payu', to='rejs.zgloszenie')),
            ],
        ),
    ]
