# Generated by Django 5.2.8 on 2026-01-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0025_platnoscpayu'),
    ]

    operations = [
        migrations.AddField(
            model_name='wplata',
            name='opis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wplata',
            name='rodzaj_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='wplata',
            name='rodzaj',
            field=models.CharField(choices=[('wplata', 'Wpłata'), ('zwrot', 'Zwrot'), ('payu', 'payu')], default=('zwrot', 'Zwrot'), max_length=7),
        ),
    ]
