# Generated by Django 5.2.8 on 2026-01-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0026_wplata_opis_wplata_rodzaj_id_alter_wplata_rodzaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='wplata',
            name='zrodlo_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
