# Generated by Django 5.2.8 on 2026-01-16 23:25

import django.utils.timezone
import rejs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0027_wplata_zrodlo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane_dodatkowe',
            name='pos4',
            field=rejs.models.EncryptedTextField(default='', max_length=100, verbose_name='miejsce urodzenia'),
        ),
        migrations.AddField(
            model_name='dane_dodatkowe',
            name='pos5',
            field=rejs.models.EncryptedTextField(default='', max_length=50, verbose_name='obywatelstwo'),
        ),
        migrations.AddField(
            model_name='dane_dodatkowe',
            name='pos6',
            field=models.DateField(default=django.utils.timezone.now, max_length=10, verbose_name='data ważności dokumentu'),
            preserve_default=False,
        ),
    ]
