# Generated by Django 5.2.8 on 2026-02-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejs', '0028_dane_dodatkowe_pos4_dane_dodatkowe_pos5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zgloszenie',
            name='adres',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='kod_pocztowy',
            field=models.CharField(max_length=12, verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='miejscowosc',
            field=models.CharField(max_length=255),
        ),
    ]
